//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LoginMsg.proto
namespace LoginMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginMsg")]
  public partial class LoginMsg : global::ProtoBuf.IExtensible
  {
    public LoginMsg() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private float _x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _size;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"size", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float size
    {
      get { return _size; }
      set { _size = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private LoginMsg.Color _color;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public LoginMsg.Color color
    {
      get { return _color; }
      set { _color = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Color")]
  public partial class Color : global::ProtoBuf.IExtensible
  {
    public Color() {}
    
    private float _r;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"r", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float r
    {
      get { return _r; }
      set { _r = value; }
    }
    private float _g;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"g", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float g
    {
      get { return _g; }
      set { _g = value; }
    }
    private float _b;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"b", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float b
    {
      get { return _b; }
      set { _b = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}