//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MoveMsg.proto
namespace MoveMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Package")]
  public partial class Package : global::ProtoBuf.IExtensible
  {
    public Package() {}
    
    private int _time = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private readonly global::System.Collections.Generic.List<Package.Action> _actions = new global::System.Collections.Generic.List<Package.Action>();
    [global::ProtoBuf.ProtoMember(2, Name=@"actions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Package.Action> actions
    {
      get { return _actions; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Action")]
  public partial class Action : global::ProtoBuf.IExtensible
  {
    public Action() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private float _dx = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dx", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float dx
    {
      get { return _dx; }
      set { _dx = value; }
    }
    private float _dy = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"dy", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float dy
    {
      get { return _dy; }
      set { _dy = value; }
    }
    private float _size = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"size", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float size
    {
      get { return _size; }
      set { _size = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}