//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Package.proto
namespace Package
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Package")]
  public partial class Package : global::ProtoBuf.IExtensible
  {
    public Package() {}
    
    private Package.Type _type = Package.Type.require;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Package.Type.require)]
    public Package.Type type
    {
      get { return _type; }
      set { _type = value; }
    }
    private byte[] _data = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"require", Value=4)]
      require = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"login", Value=1)]
      login = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"status", Value=2)]
      status = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"quit", Value=3)]
      quit = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"move", Value=5)]
      move = 5
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}