//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RequireMsg.proto
namespace RequireMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequireMsg")]
  public partial class RequireMsg : global::ProtoBuf.IExtensible
  {
    public RequireMsg() {}
    
    private RequireMsg.RequireType _require;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"require", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public RequireMsg.RequireType require
    {
      get { return _require; }
      set { _require = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"RequireType")]
    public enum RequireType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"id", Value=1)]
      id = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"status", Value=2)]
      status = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ranks", Value=3)]
      ranks = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}