# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MoveMsg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MoveMsg.proto',
  package='',
  serialized_pb='\n\rMoveMsg.proto\"u\n\x07Package\x12\x0c\n\x04time\x18\x01 \x01(\x05\x12 \n\x07\x61\x63tions\x18\x02 \x03(\x0b\x32\x0f.Package.Action\x1a:\n\x06\x41\x63tion\x12\n\n\x02id\x18\x01 \x01(\x05\x12\n\n\x02\x64x\x18\x02 \x01(\x02\x12\n\n\x02\x64y\x18\x03 \x01(\x02\x12\x0c\n\x04size\x18\x04 \x01(\x02')




_PACKAGE_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='Package.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Package.Action.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dx', full_name='Package.Action.dx', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dy', full_name='Package.Action.dy', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='Package.Action.size', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=76,
  serialized_end=134,
)

_PACKAGE = _descriptor.Descriptor(
  name='Package',
  full_name='Package',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='Package.time', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actions', full_name='Package.actions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PACKAGE_ACTION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=17,
  serialized_end=134,
)

_PACKAGE_ACTION.containing_type = _PACKAGE;
_PACKAGE.fields_by_name['actions'].message_type = _PACKAGE_ACTION
DESCRIPTOR.message_types_by_name['Package'] = _PACKAGE

class Package(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Action(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PACKAGE_ACTION

    # @@protoc_insertion_point(class_scope:Package.Action)
  DESCRIPTOR = _PACKAGE

  # @@protoc_insertion_point(class_scope:Package)


# @@protoc_insertion_point(module_scope)
