# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Package.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Package.proto',
  package='',
  serialized_pb='\n\rPackage.proto\"t\n\x07Package\x12\x1b\n\x04type\x18\x01 \x01(\x0e\x32\r.Package.Type\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\">\n\x04Type\x12\x0b\n\x07require\x10\x04\x12\t\n\x05login\x10\x01\x12\n\n\x06status\x10\x02\x12\x08\n\x04quit\x10\x03\x12\x08\n\x04move\x10\x05')



_PACKAGE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='Package.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='require', index=0, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='login', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='status', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='quit', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='move', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=71,
  serialized_end=133,
)


_PACKAGE = _descriptor.Descriptor(
  name='Package',
  full_name='Package',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Package.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=4,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='Package.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PACKAGE_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=17,
  serialized_end=133,
)

_PACKAGE.fields_by_name['type'].enum_type = _PACKAGE_TYPE
_PACKAGE_TYPE.containing_type = _PACKAGE;
DESCRIPTOR.message_types_by_name['Package'] = _PACKAGE

class Package(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PACKAGE

  # @@protoc_insertion_point(class_scope:Package)


# @@protoc_insertion_point(module_scope)
