# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RequireMsg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RequireMsg.proto',
  package='',
  serialized_pb='\n\x10RequireMsg.proto\"d\n\nRequireMsg\x12(\n\x07require\x18\x01 \x02(\x0e\x32\x17.RequireMsg.RequireType\",\n\x0bRequireType\x12\x06\n\x02id\x10\x01\x12\n\n\x06status\x10\x02\x12\t\n\x05ranks\x10\x03')



_REQUIREMSG_REQUIRETYPE = _descriptor.EnumDescriptor(
  name='RequireType',
  full_name='RequireMsg.RequireType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='id', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='status', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ranks', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=76,
  serialized_end=120,
)


_REQUIREMSG = _descriptor.Descriptor(
  name='RequireMsg',
  full_name='RequireMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='require', full_name='RequireMsg.require', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUIREMSG_REQUIRETYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=120,
)

_REQUIREMSG.fields_by_name['require'].enum_type = _REQUIREMSG_REQUIRETYPE
_REQUIREMSG_REQUIRETYPE.containing_type = _REQUIREMSG;
DESCRIPTOR.message_types_by_name['RequireMsg'] = _REQUIREMSG

class RequireMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUIREMSG

  # @@protoc_insertion_point(class_scope:RequireMsg)


# @@protoc_insertion_point(module_scope)
